set(headers ${headers}
	include/InGamePatcherAPI.h
	src/api/VREditorPapyrusAPI.h
	src/PCH.h
    src/log.h
    src/IFrameUpdateListener.h
    src/FrameCallbackDispatcher.h
    src/EditModeManager.h
    src/EditModeInputManager.h
    src/EditModeTransitioner.h
    src/EditModeStateManager.h
    src/TutorialManager.h
    src/util/InputManager.h
    src/util/MessageBoxUtil.h
    src/util/MenuChecker.h
    src/util/NotificationManager.h
    src/util/PositioningUtil.h
    src/util/Raycast.h
    src/util/SelectionLogger.h
    src/util/ActionLogger.h
    src/util/TouchingObjectsFinder.h
    src/util/VRNodes.h
    src/util/UUID.h
    src/visuals/RaycastRenderer.h
    src/visuals/ObjectHighlighter.h
    src/actions/Action.h
    src/actions/ActionHistoryRepository.h
    src/actions/UndoRedoController.h
    src/actions/DeleteHandler.h
    src/actions/SnapToGroundHandler.h
    src/actions/CopyHandler.h
    src/selection/SelectionState.h
    src/selection/HoverStateManager.h
    src/selection/DelayedHighlightRefreshManager.h
    src/selection/ConsoleManager.h
    src/ui/SelectionMenu.h
    src/ui/SelectionMenuHelpers.h
    src/ui/MenuStateManager.h
    src/ui/MenuViewportManager.h
    src/grab/TransformSmoother.h
    src/grab/RemoteGrabController.h
    src/grab/RemoteSelectionController.h
    src/grab/RemoteNPCPlacementManager.h
    src/grab/DeferredCollisionUpdateManager.h
    src/interfaces/higgsinterface001.h
    src/interfaces/ThreeDUIInterface001.h
    src/persistence/FormKeyUtil.h
    src/persistence/EntryMetadata.h
    src/persistence/ChangedObjectRegistry.h
    src/persistence/SaveGameDataManager.h
    src/persistence/BaseObjectSwapperParser.h
    src/persistence/BaseObjectSwapperExporter.h
    src/persistence/AddedObjectsParser.h
    src/persistence/AddedObjectsSpawner.h
    src/persistence/AddedObjectsExporter.h
    src/persistence/CreatedObjectTracker.h
    src/gallery/GalleryItem.h
    src/gallery/GalleryManager.h
    src/gallery/GalleryPlacementUtil.h
    src/test/SaveFileTestManager.h
    src/config/ConfigStorage.h
    src/config/ConfigStoragePapyrusAdapter.h
    src/config/ConfigOptions.h
    external/VRManagerAPI.h
    external/PapyrusVRTypes.h
    external/VRHookAPI.h
    external/PapyrusVRAPI.h
    external/OpenVRTypes.h
)
