set(sources ${sources}
    src/plugin.cpp
    src/api/InGamePatcherAPI.cpp
    src/api/VREditorPapyrusAPI.cpp
    src/api/VRBuilderNativePapyrusAPI.cpp
    src/FrameCallbackDispatcher.cpp
    src/ui/MenuStateManager.cpp
    src/EditModeManager.cpp
    src/EditModeInputManager.cpp
    src/EditModeTransitioner.cpp
    src/EditModeStateManager.cpp
    src/TutorialManager.cpp
    src/util/InputManager.cpp
    src/util/MessageBoxUtil.cpp
    src/util/MenuChecker.cpp
    src/util/NotificationManager.cpp
    src/util/PositioningUtil.cpp
    src/util/Raycast.cpp
    src/util/SelectionLogger.cpp
    src/util/ActionLogger.cpp
    src/util/TouchingObjectsFinder.cpp
    src/util/RotationMath.cpp
    src/util/SkyrimNetInterface.cpp
    src/visuals/RaycastRenderer.cpp
    src/visuals/ObjectHighlighter.cpp
    src/actions/ActionHistoryRepository.cpp
    src/actions/UndoRedoController.cpp
    src/selection/SelectionState.cpp
    src/selection/HoverStateManager.cpp
    src/selection/SphereHoverStateManager.cpp
    src/selection/DelayedHighlightRefreshManager.cpp
    src/selection/ConsoleManager.cpp
    src/selection/ObjectFilter.cpp
    src/grab/TransformSmoother.cpp
    src/grab/RemoteGrabController.cpp
    src/grab/RemoteSelectionController.cpp
    src/grab/SphereSelectionController.cpp
    src/grab/RemoteNPCPlacementManager.cpp
    src/grab/DeferredCollisionUpdateManager.cpp
    src/grab/GroupMoveResolver.cpp
    src/grab/ThumbstickAccelerationHelper.cpp
    src/grab/RemoteGrabTransformCalculator.cpp
    src/grab/HandRotationTransformer.cpp
    src/grab/HandTranslationTransformer.cpp
    src/grab/SnapToGridController.cpp
    src/interfaces/higgsinterface001.cpp
    src/interfaces/ThreeDUIInterface001.cpp
    src/persistence/FormKeyUtil.cpp
    src/persistence/EntryMetadata.cpp
    src/persistence/ChangedObjectRegistry.cpp
    src/persistence/SaveGameDataManager.cpp
    src/persistence/BaseObjectSwapperParser.cpp
    src/persistence/BaseObjectSwapperExporter.cpp
    src/persistence/AddedObjectsParser.cpp
    src/persistence/AddedObjectsSpawner.cpp
    src/persistence/AddedObjectsExporter.cpp
    src/persistence/SpriggitExporter.cpp
    src/persistence/CreatedObjectTracker.cpp
    src/gallery/GalleryManager.cpp
    src/gallery/GalleryPlacementUtil.cpp
    src/config/ConfigStorage.cpp
    src/config/ConfigOptions.cpp
    external/PapyrusVRTypes.cpp
)
